### ISSUE TITLE
为什么全局准确率这么低呢？

### ISSUE THREAD

**Issue by Bhongcheng** [JianXu95/FedPAC#1]
对不起，问题解决了

**Comment by JianXu95** [comment]
您好，


我默认不学习全局模型，所以聚合的时候没有考虑全局的classifier head，代码中global model只负责传递更新的feature extractor，这样子在不同group的client之间label顺序不同的时候，也能只进行group内classifier head聚合。但在不考虑concept shift等特殊情况下，聚合本地的classifier head当然也能得到一个global model，再将这个global model本地微调应该也能差不多不错的个性化模型。按理说全局模型虽然不一定很好，也不至于这样才对。有可能是因为代码里面，为了方便直接将聚合后的参数传递给client了，没有同时更新全局变量的global model。


以及，更好理解全局模型和本地模型关系的话，推荐可以看Fed-RoD这篇论文。主要得考虑出发点是什么，如果想学习一个更好的全局模型，那可能我当前的框架不见得有效，当然，一个更好的全局模型往往也能带来更好的本地个性化模型。我也做过一个简单的工作是试图学习更好的全局模型的：https://arxiv.org/abs/2303.06314


祝好！


| |
徐健
|
|
***@***.***
|
在2023年5月7日 ***@***.***> 写道：

您好，您的论文是针对个性化联邦学习的，评价的指标是本地准确率。然而当我加了一段代码尝试去观察全局准确率的时候，以论文中的CIFAR10实验为例（FedAvg 20 clients），我发现全局准确率特别低，我很疑惑这是否正常，您能说说为什么吗？


结果图


谢谢您！

**Comment by Bhongcheng** [comment]
谢谢您的回复，我想再向您请教一些事情。
您的论文中提到的Feature Alignment虽然是应用到个性化邻邦学习中，但像您所说这样做是为了训练一个适用于所有客户的更好的共享特征（个人浅薄理解，如若有误恳请指点），是不是对全局模型也是有增益的呢？因此我觉得您的框架也可以继续拓展，在已有的个性化基础上再得到一个全局模型。与此同时，全局模型性能的提升同样增强个性化联邦学习呢？
谢谢您！

**Comment by JianXu95** [comment]
虽然我觉得这样想没问题，但是，好像已经有些论文做差不多的事情了 :( 
我是21年底就做的论文，事实证明22年类似思想被使用和完善的也挺多= =
以下是我注意到过的：
https://openreview.net/forum?id=29V3AWjVAFi
https://arxiv.org/abs/2211.09299
https://arxiv.org/abs/2210.07615


以及请问你是哪儿的同学呀？


| |
徐健
|
|
***@***.***
|
在2023年5月7日 ***@***.***> 写道：

谢谢您的回复，我想再向您请教一些事情。
您的论文中提到的Feature Alignment虽然是应用到个性化邻邦学习中，但像您所说这样做是为了训练一个适用于所有客户的更好的共享特征（个人浅薄理解，如若有误恳请指点），是不是对全局模型也是有增益的呢？因此我觉得您的框架也可以继续拓展，在已有的个性化基础上再得到一个全局模型。与此同时，全局模型性能的提升同样增强个性化联邦学习呢？
谢谢您！

**Comment by Bhongcheng** [comment]
再说句题外话。。 其实您那篇FL与Balanced SoftMax的论文我先前看过。因为先前我通过实验发现在FL中BSM可能存在的问题，我想的真的和您在论文中的动机和举的例子一致！但是我能力太差，想的方法有问题，而您论文中提出的方法就非常的好！
    说来也很巧，我也是在看您FedPAC论文后想找您请求代码，然后发现您的这片FL与BSM的论文，发现我们有部分的想法是一样的。回过头来看我自己的想法就完全没有道理。

**Comment by Bhongcheng** [comment]
> 虽然我觉得这样想没问题，但是，好像已经有些论文做差不多的事情了 :( 我是21年底就做的论文，事实证明22年类似思想被使用和完善的也挺多= = 以下是我注意到过的： https://openreview.net/forum?id=29V3AWjVAFi https://arxiv.org/abs/2211.09299 https://arxiv.org/abs/2210.07615 以及请问你是哪儿的同学呀？ | | 徐健 | | ***@***.*** | 在2023年5月7日 ***@***.***> 写道： 谢谢您的回复，我想再向您请教一些事情。 您的论文中提到的Feature Alignment虽然是应用到个性化邻邦学习中，但像您所说这样做是为了训练一个适用于所有客户的更好的共享特征（个人浅薄理解，如若有误恳请指点），是不是对全局模型也是有增益的呢？因此我觉得您的框架也可以继续拓展，在已有的个性化基础上再得到一个全局模型。与此同时，全局模型性能的提升同样增强个性化联邦学习呢？ 谢谢您！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我是北京交通大学软件学院2021级学硕，我的导师是清华大学出身，我导师的大老板是张尧学院士

**Comment by JianXu95** [comment]
哦哦，你好呀！我叫徐健，在浙大读了本硕的，所以应该比你大好几届哈哈，差不多明年博士毕业，现在在美国访学 半夜准备睡了，以后有机会再交流~


| |
徐健
|
|
***@***.***
|
在2023年5月7日 ***@***.***> 写道：

虽然我觉得这样想没问题，但是，好像已经有些论文做差不多的事情了 :( 我是21年底就做的论文，事实证明22年类似思想被使用和完善的也挺多= = 以下是我注意到过的： https://openreview.net/forum?id=29V3AWjVAFihttps://arxiv.org/abs/2211.09299https://arxiv.org/abs/2210.07615 以及请问你是哪儿的同学呀？ | | 徐健 | | @.*** | 在2023年5月7日 @.> 写道： 谢谢您的回复，我想再向您请教一些事情。 您的论文中提到的Feature Alignment虽然是应用到个性化邻邦学习中，但像您所说这样做是为了训练一个适用于所有客户的更好的共享特征（个人浅薄理解，如若有误恳请指点），是不是对全局模型也是有增益的呢？因此我觉得您的框架也可以继续拓展，在已有的个性化基础上再得到一个全局模型。与此同时，全局模型性能的提升同样增强个性化联邦学习呢？ 谢谢您！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

我是北京交通大学软件学院2021级学硕，我的导师是清华大学出身，我导师的大老板是张尧学院士
